plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT' apply false
	id 'glue' version '0.0.7'
	id 'maven-publish'
}

glue {
	// subproject names in the order they'll be glued
	targets = ['legacy', 'legacy2', 'legacy3', 'main', 'glue']
	// output path defaults to build/libs/archives_base_name-mod_version.jar
	outputName = "${project.archives_base_name}-${project.mod_version}-universal"
}

allprojects {
	version = rootProject.mod_version
	group = rootProject.maven_group
}

subprojects {
	apply plugin: 'fabric-loom'

	dependencies {
		minecraft "com.mojang:minecraft:${project.minecraft_version}"
		mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
		modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	}

	base {
		archivesName = project.archives_base_name
	}

	processResources {
		inputs.property 'version', project.version

		filesMatching('fabric.mod.json') {
			expand 'version': inputs.properties.version
		}
	}

	jar {
		inputs.property 'archivesName', project.base.archivesName

		from('../LICENSE') {
			rename { "${it}_${inputs.properties.archivesName}" }
		}
	}

	java {
		targetCompatibility = sourceCompatibility = project.java_version as Integer
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = project.java_version as Integer
	}
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			artifactId = project.archives_base_name
			assert tasks.glue.outputs.files.size() == 1
			artifact tasks.glue.outputs.files.first()
		}
	}
}

tasks.withType(AbstractPublishToMaven).configureEach { dependsOn('glue') }
