pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = "Fourmisain's Maven"
			url = 'https://gitlab.com/api/v4/projects/37712942/packages/maven'
		}
		gradlePluginPortal()
	}
}

include 'glue'
include '1_14'
include '1_16'
include '1_20_5'
include '1_21_2'
include '1_21_5'
include '26_1'

rootProject.name = archives_base_name
